"""Dish templates, drawn as 16x16 text grids, one character per pixel.

  .        transparent
  A-Z      fixed base-layer colours from the dish's own `pal`
  0-7      main flavour layer, palette slot 0-7 (see palettes.py)
  a-h      second flavour layer, palette slot 0-7 (a=0 ... h=7)

`layers` names the texture of each part. `order` is the draw order, bottom first. `flavors` says which
custom_model_data string each flavour layer follows; the second layer falls back to the main flavour when a
dish has only one. `defaults` are the flavours shown on a stack that was never cooked, such as one taken
from the creative menu.
"""

BOWL = {
	"A": "#7E5A1A", "B": "#674914", "C": "#553C0E", "D": "#45300B", "E": "#36250A",
	"F": "#3A2808", "G": "#1C1303",
}

DISHES = {}

DISHES["stew"] = dict(
	layers={"base": "bowl", "a": "broth", "b": "chunks"},
	order=["base", "a", "b"],
	defaults=["beef", "carrot"],
	refs=["mushroom_stew", "rabbit_stew", "bowl"],
	pal=BOWL,
	grid="""
................
................
................
......fg.fg.....
.....FbcgbcG....
...FF011222GG...
..F01bc122233G..
.F112cd223bc34G.
.FAAABBBBBBCCDG.
.FBCCCCDCCCDDEG.
..FCCDCCCDDDEG..
...FDDDDEDEEG...
....FGGGGGGG....
................
................
................
""")

SPONGE = {
	"P": "#F6DFA0", "S": "#E6C27A", "T": "#CFA45C", "U": "#B0843E", "V": "#8E6430", "W": "#5C3C18",
}

DISHES["cake"] = dict(
	layers={"base": "sponge", "a": "frosting", "b": "fruit"},
	order=["base", "a", "b"],
	defaults=["sweet_berry", "sweet_berry"],
	refs=["cake", "pumpkin_pie", "bread"],
	pal=SPONGE,
	grid="""
................
................
................
..........556...
.......5501ab26.
....55011ab1cd6.
.55001112cd2236.
.53322232333446.
.VPSS3SSSSTS4TW.
.VSSSSSTSSSTTUW.
.V3222223222346.
.VSTSSSSTSSTTUW.
.VTTUTTTTUTUUUW.
..WWWWWWWWWWWWW.
................
................
""")

STICK = {"T": "#896727", "U": "#684E1E", "V": "#493615", "W": "#281E0B"}

DISHES["skewer"] = dict(
	layers={"base": "stick", "a": "chunks", "b": "middle"},
	order=["base", "a", "b"],
	defaults=["beef", "carrot"],
	refs=["cooked_beef", "carrot", "stick"],
	pal=STICK,
	grid="""
...............T
..........5556T.
.........501126.
.........511236.
.........512236.
......fffg23346.
.....fabccg666..
.....fbccdg.....
.....fbcddg.....
..555fcddeg.....
.50122gggg......
.512326.........
.522346.........
.523446.........
.T6666..........
V...............
""")

BREAD = {
	"H": "#F2DCA6", "C": "#E6C68A", "J": "#CFA868", "K": "#C08436", "R": "#9A6424", "Q": "#6E4818",
	"P": "#7A5420", "O": "#4A320E",
}

DISHES["sandwich"] = dict(
	layers={"base": "bread", "a": "filling", "b": "bits"},
	order=["base", "a", "b"],
	defaults=["porkchop"],
	refs=["bread", "cooked_porkchop", "cake"],
	pal=BREAD,
	grid="""
................
................
....PPPPPPPP....
..PPKKKKKKKKOO..
.PKKHHCCCCCCRRO.
.PKHCCCCCCCCJRO.
.PKCCCJCCCCJJRO.
..PKCCCCCCJJRO..
..PRRRRRRRRRQO..
.50112b1122a236.
..5233c2223c346.
..PKKKRRRRRRQO..
..PQQQQQQQQQQO..
...OOOOOOOOOO...
................
................
""")

KELP = {
	"H": "#6E6A5A", "K": "#57503F", "L": "#3C3324", "M": "#2E2820", "N": "#473F31",
	"X": "#26231E", "Y": "#0F0E0C",
}

DISHES["kelp_roll"] = dict(
	layers={"base": "wrap", "a": "filling"},
	order=["base", "a"],
	defaults=["salmon"],
	refs=["dried_kelp", "cooked_salmon", "cooked_cod"],
	pal=KELP,
	grid="""
................
................
.........XXXX...
........XK01KY..
.......XK0122KY.
.......XK1233KY.
....XXXXLK34KMY.
...XK01KYLNLMMY.
..XK0122KYYYYY..
..XK1233KY......
..XLK34KMY......
..XLLNLMMY......
...YYYYYY.......
................
................
................
""")

DISHES["salad"] = dict(
	layers={"base": "bowl", "a": "pieces", "b": "top"},
	order=["base", "a", "b"],
	defaults=["apple", "sweet_berry"],
	refs=["bowl", "beetroot_soup", "sweet_berries"],
	pal=BOWL,
	grid="""
................
................
......5566......
....5501ab26....
...501bc12ab6...
..5011cd12cd36..
..F1225122343G..
.F12abc23ab346G.
.FAAABBBBBBCCDG.
.FBCCCCDCCCDDEG.
..FCCDCCCDDDEG..
...FDDDDEDEEG...
....FGGGGGGG....
................
................
................
""")

DISHES["soup"] = dict(
	layers={"base": "bowl", "a": "broth", "b": "garnish"},
	order=["base", "a", "b"],
	defaults=["pumpkin", "carrot"],
	refs=["beetroot_soup", "mushroom_stew", "bowl"],
	pal=BOWL,
	grid="""
................
................
................
................
.....FFGGGG.....
...FF001122GG...
..F011b12223dG..
.F1122223c2334G.
.FAAABBBBBBCCDG.
.FBCCCCDCCCDDEG.
..FCCDCCCDDDEG..
...FDDDDEDEEG...
....FGGGGGGG....
................
................
................
""")

BOTTLE = {
	"W": "#D4E5F7", "V": "#B3CFEC", "G": "#5D8FC2", "B": "#3E6A9A",
	"C": "#C8955A", "D": "#9A6A38", "E": "#6E4824",
}

DISHES["juice"] = dict(
	layers={"base": "bottle", "a": "liquid"},
	order=["base", "a"],
	defaults=["melon"],
	refs=["honey_bottle", "glass_bottle", "melon_slice"],
	pal=BOTTLE,
	grid="""
................
......CCCD......
......DDDE......
......VWVB......
......GVVB......
.....GVW1VB.....
....GV01122B....
...GW0111222B...
...G01122223B...
...G11222233B...
...G12222333B...
...G12223334B...
....G223344B....
.....BBBBBB.....
................
................
""")

CRUST = {
	"H": "#F2C682", "K": "#DDA35A", "L": "#B97A3A", "M": "#9C6430", "U": "#84522A",
	"N": "#7A4A1E", "O": "#4A2A0E",
}

DISHES["pie"] = dict(
	layers={"base": "crust", "a": "filling"},
	order=["base", "a"],
	defaults=["apple"],
	refs=["pumpkin_pie", "cookie", "bread"],
	pal=CRUST,
	grid="""
................
................
................
................
.....NNNNNN.....
...NHHKKKKKLO...
..NH0K1122K2LO..
.NH01K1222K23LO.
.NKKKKKKKKKKKLO.
.NK12K2233K34LO.
.NMLLLLLLLLLLMO.
..OMMUMMMMUMMO..
...OMMMMMMMMOO..
.....OOOOOO.....
................
................
""")

DOUGH = {
	"H": "#F0A860", "K": "#E89850", "L": "#D9833E", "M": "#B97335", "U": "#8E5428", "N": "#8B4B2B",
	"O": "#452A13",
}

DISHES["cookies"] = dict(
	layers={"base": "dough", "a": "chips"},
	order=["base", "a"],
	defaults=["chocolate"],
	refs=["cookie", "cocoa_beans", "bread"],
	pal=DOUGH,
	grid="""
................
................
................
....NNNNNNNO....
..NNHHK4KKKKOO..
.NHK3KKKKK6KLLO.
.NK4KKKLK3KLLMO.
.NKKK6KKKKLL4MO.
..NLKKK3KLLLMO..
..NMMMMMMMMMMO..
.NUUUUUUUUUUUUO.
.NLMM4MMMMMMMMO.
..NUUUUUUUUUUO..
..NLMMMMM3MMMO..
...OOOOOOOOOO...
................
""")

EGG = {
	"H": "#FFF0A0", "K": "#F6D85A", "L": "#E8BE3A", "M": "#C89A22", "S": "#DDB040",
	"N": "#A07818", "O": "#6E5010",
}

DISHES["omelette"] = dict(
	layers={"base": "egg", "a": "filling"},
	order=["base", "a"],
	defaults=["mushroom"],
	refs=["egg", "baked_potato", "cooked_chicken"],
	pal=EGG,
	grid="""
................
................
................
................
....556..5566...
..N501266501236.
.NHHKKKKKKKKLLO.
.NHKKKSKKKKLLMO.
.NKKKKKKKSKLLMO.
..NKKSKKKKLLMO..
...NLLLLLLLMO...
.....OOOOOOO....
................
................
................
................
""")

SEAR = {"S": "#3A1E0E"}

DISHES["roast"] = dict(
	layers={"base": "sear", "a": "main", "b": "side"},
	order=["a", "b", "base"],
	defaults=["beef", "potato"],
	refs=["cooked_porkchop", "cooked_mutton", "baked_potato"],
	pal=SEAR,
	grid="""
................
................
.....55556......
...5501112266...
..501112223236..
.5011S12223336..
.5112S2S233346..
.512222S2334466.
.5122S22334ffg6.
..5233S334fabcg.
..5223334fabcdg.
...56666fbccdeg.
.......fgcdeeg..
........ggggg...
................
................
""")

MUSH = {
	"A": "#8A7E6A", "B": "#74684F", "C": "#5E5440", "D": "#4A4232", "E": "#383226",
	"F": "#50473A", "G": "#221E16", "H": "#A89A80",
}

DISHES["dubious_mush"] = dict(
	layers={"base": "lump"},
	order=["base"],
	refs=["rotten_flesh", "brown_mushroom", "poisonous_potato"],
	pal=MUSH,
	grid="""
................
................
................
................
.....FFG........
...FFABBGFFG....
..FABBCBBAABG...
.FABCCBHCBBCCG..
.FBCCDCCCCDCDG..
FBCDCCDCHCDDDEG.
FCCDDCDDDDDEEG..
.GDDEDDEEEEEGG..
..GGGGGGGGGG....
................
................
................
""")
