"""Dish templates, drawn as 16x16 text grids, one character per pixel.

  .        transparent
  A-Z      fixed base-layer colours from the dish's own `pal`
  0-7      main flavour layer, palette slot 0-7 (see palettes.py)
  a-h      second flavour layer, palette slot 0-7 (a=0 ... h=7)

`art` names a full-colour PNG in tools/textures/art/ used as the base layer instead of drawn base pixels. Its
grid marks those pixels with `#` and only spells out the flavour pixels, which replace the art underneath.

`vanilla` names a vanilla item sprite (bowl, cookie, ...) the dish is drawn on: the item definition puts the
game's own sprite under the flavour layers, so dishes with a vanilla counterpart look like it and follow resource
packs. Grids of those dishes only hold the overlay pixels.

`layers` names the texture of each part. `order` is the draw order, bottom first, with "vanilla" for the vanilla
sprite. `flavors` says which custom_model_data string each flavour layer follows; the second layer falls back to the
main flavour when a dish has only one. `raw` marks dishes made without cooking, which also get the raw_ palettes of
their meat, fish and potato. `defaults` are the flavours shown on a stack that was never cooked, such as one taken
from the creative menu.

`pot` is how a dish made in the cooking pot and served in a container looks from above while it waits in the pot,
drawn in the middle 8x8 pixels with the same layers. The pot draws it over its contents, so a finished soup looks
like soup rather than the ingredients it was cooked from.
"""

DISHES = {}

# Bowl dishes sit in the vanilla bowl: rim on row 5, the inside on rows 6-8 (x5-10, x3-11, x5-10).

DISHES["stew"] = dict(
	vanilla="bowl",
	layers={"a": "broth", "b": "chunks"},
	order=["vanilla", "a", "b"],
	defaults=["beef"],
	refs=["rabbit_stew", "mushroom_stew", "bowl"],
	pot="""
................
................
................
................
....2bc22322....
....3cd2bc22....
....2223cd32....
....bc222222....
....cd23bc22....
....3222cd23....
....22bc2222....
....32cd2232....
................
................
................
................
""",
	grid="""
................
................
................
................
................
......bc12......
.....01cd12.....
...0112ab223....
.....2bc334.....
................
................
................
................
................
................
................
""")

DISHES["soup"] = dict(
	vanilla="bowl",
	layers={"a": "broth", "b": "garnish"},
	order=["vanilla", "a", "b"],
	defaults=["pumpkin", "carrot"],
	refs=["beetroot_soup", "mushroom_stew", "bowl"],
	pot="""
................
................
................
................
....22122222....
....2bc22312....
....21c22222....
....22222bc2....
....13222cd2....
....222b2222....
....2bcd2212....
....22222222....
................
................
................
................
""",
	grid="""
................
................
................
................
................
................
.....01bc22.....
...011cdd223....
.....223334.....
................
................
................
................
................
................
................
""")

DISHES["salad"] = dict(
	raw=True,
	vanilla="bowl",
	layers={"a": "pieces", "b": "top"},
	order=["vanilla", "a", "b"],
	defaults=["apple", "sweet_berry"],
	refs=["bowl", "rabbit_stew", "sweet_berries"],
	grid="""
................
................
................
.......556......
.....5ef0126....
....5bcf1236....
.....ab2bc3.....
...12cd23ab3....
.....3d34cd.....
................
................
................
................
................
................
................
""")

# The liquid fills the inside of the vanilla glass bottle, below its highlights.
DISHES["juice"] = dict(
	raw=True,
	vanilla="glass_bottle",
	layers={"a": "liquid"},
	order=["vanilla", "a"],
	defaults=["melon"],
	refs=["honey_bottle", "potion", "melon_slice"],
	grid="""
................
................
................
................
................
................
................
................
................
.....1.01222....
.....1.12223....
.....12223.3....
.....22334.4....
......334.4.....
................
................
""")

# Recolours the chips of the vanilla cookie, so cocoa cookies look like the vanilla one.
DISHES["cookies"] = dict(
	vanilla="cookie",
	layers={"a": "chips"},
	order=["vanilla", "a"],
	defaults=["chocolate"],
	refs=["cookie", "cocoa_beans", "sweet_berries"],
	grid="""
................
................
................
......4.........
................
....3..24.......
..3....34.3.....
.....2..........
.....4..........
.......24..3....
....3...........
.........4......
................
................
................
................
""")

# Recolours the filling of the vanilla pumpkin pie: top surface and the cut face.
DISHES["pie"] = dict(
	vanilla="pumpkin_pie",
	layers={"a": "filling"},
	order=["vanilla", "a"],
	defaults=["pumpkin"],
	refs=["pumpkin_pie", "apple", "sweet_berries"],
	grid="""
................
................
................
................
................
................
.....122221.....
...1221111221...
...2101341122...
..11333411221...
..3333402221....
..333..1........
................
................
................
................
""")

# Recolours the fruit on top of the vanilla cake.
DISHES["cake"] = dict(
	vanilla="cake",
	layers={"a": "fruit"},
	order=["vanilla", "a"],
	defaults=["sweet_berry"],
	refs=["cake", "sweet_berries", "glow_berries"],
	grid="""
................
................
................
.....3.22.......
...3..2123.3....
.......22....2..
....2...........
..........2.....
................
................
................
................
................
................
................
................
""")

# Three chunks centred on a stick that runs corner to corner, in the vanilla stick colours.
STICK = {"T": "#896727", "U": "#684E1E", "V": "#493615", "W": "#281E0B"}

DISHES["skewer"] = dict(
	raw=True,
	layers={"base": "stick", "a": "chunks", "b": "middle"},
	order=["base", "a", "b"],
	defaults=["beef", "carrot"],
	refs=["stick", "sweet_berries", "cooked_beef"],
	pal=STICK,
	grid="""
..............VW
...........556TW
..........50416.
..........51346.
..........54236.
.......ffgT666..
......faebg.....
......fbedg.....
......fedeg.....
...556Tggg......
..50416.........
..51346.........
..54236.........
.VT666..........
VUW.............
WW..............
""")

# Two filling layers between the slices: the main ingredient at the bottom, the second on top of it.
DISHES["sandwich"] = dict(
	raw=True,
	art="sandwich.png",
	layers={"base": "bread", "a": "filling", "b": "second"},
	order=["base", "a", "b"],
	defaults=["porkchop"],
	refs=["bread", "cooked_porkchop", "cake"],
	grid="""
................
................
.....######.....
...##########...
..############..
.##############.
.##############.
.##############.
.##############.
.fabbcbbcbccdcg.
.51222322232336.
.##############.
..############..
................
................
................
""")

DISHES["kelp_roll"] = dict(
	raw=True,
	art="kelp_roll.png",
	layers={"base": "wrap", "a": "filling", "b": "second"},
	order=["base", "a", "b"],
	defaults=["salmon", "carrot"],
	refs=["dried_kelp", "cooked_salmon", "cooked_cod"],
	grid="""
................
................
.....######.....
....#211112#....
...#10babd13#...
...#20bdce13#...
...##42333###...
...##########...
...##########...
...##########...
....########....
......####......
................
................
................
................
""")

EGG = {
	"A": "#6A4A12", "B": "#F4DC86", "C": "#E9C257", "D": "#D6A53A", "G": "#B07F22", "H": "#8A5E16",
}

# A flat folded omelette. The filling shows in the fold along its side, with a few bits of the second on top.
DISHES["omelette"] = dict(
	layers={"base": "egg", "a": "filling", "b": "chunks"},
	order=["base", "a", "b"],
	defaults=["mushroom"],
	refs=["egg", "baked_potato", "bread"],
	pal=EGG,
	grid="""
................
................
................
................
................
................
................
....AAAAAAAA....
..AABBBCCCCDAA..
.ABCCacCCCCCDGA.
.ACCCCCCDDcDDGA.
.AH24HH224H24HA.
.ADCCDDDDDDDDGA.
..AAAAAAAAAAAA..
................
................
""")

# Meat roasts show a roasted joint on the bone instead, with the side pieces next to it.
MEATS = ["beef", "chicken", "mutton", "porkchop", "rabbit", "rotten_flesh"]

DISHES["roast"] = dict(
	variant=dict(dish="roast_meat", flavors=MEATS),
	layers={"a": "main", "b": "side"},
	order=["a", "b"],
	defaults=["beef", "potato"],
	refs=["cooked_porkchop", "cooked_mutton", "baked_potato"],
	grid="""
................
................
................
...555566.......
..50113226......
.5013122336.....
.5112123236ffg..
.512231334fabcg.
.513223334fcbdg.
..52343446fcdeg.
...6666ffg.ggg..
......fabcg.....
......fbdcg.....
......fcdeg.....
.......ggg......
................
""")


BONE = {"W": "#EFE9D6", "V": "#D6CCAE", "U": "#ADA080", "Q": "#6E6450"}

DISHES["roast_meat"] = dict(
	variant_of="roast",
	layers={"base": "bone", "a": "joint", "b": "side"},
	order=["a", "base", "b"],
	defaults=["beef", "potato"],
	refs=["cooked_chicken", "cooked_mutton", "baked_potato"],
	pal=BONE,
	grid="""
................
................
.......555566...
.....550113126..
....5013112236..
...50111232336..
...51132123346..
...51223234346..
...52233434ffg..
....534466fabcg.
....V566ffgcbdg.
...WV..fabcgdeg.
.WWV...fbdcggg..
WWVQ...fcdeg....
.WQ.....ggg.....
................
""")
MUSH = {"A": "#2A2119", "B": "#928C52", "C": "#B2AA70", "D": "#5C5838", "E": "#767240", "F": "#45392F"}

# Two grey-green lumps in the vanilla bowl.
DISHES["dubious_mush"] = dict(
	vanilla="bowl",
	layers={"base": "lump"},
	order=["vanilla", "base"],
	refs=["bowl", "rotten_flesh", "brown_mushroom"],
	pal=MUSH,
	pot="""
................
................
................
................
....DEEBDDED....
....EBCCEDFD....
....DEBEEDDE....
....FDDEDBCE....
....DEEDEBBD....
....EBCDFDED....
....DDBEEDDF....
....EDDDEDED....
................
................
................
................
""",
	grid="""
................
................
................
................
................
.....AAA.AAA....
....ABCCDECBA...
..ABBBEEEDDEEA..
.....DDDDDF.....
................
................
................
................
................
................
................
""")
