"""Dish templates, drawn as 16x16 text grids, one character per pixel.

  .        transparent
  A-Z      fixed base-layer colours from the dish's own `pal`
  0-7      main flavour layer, palette slot 0-7 (see palettes.py)
  a-h      second flavour layer, palette slot 0-7 (a=0 ... h=7)

`vanilla` names a vanilla item sprite (bowl, cookie, ...) the dish is drawn on: the item definition puts the
game's own sprite under the flavour layers, so dishes with a vanilla counterpart look like it and follow resource
packs. Grids of those dishes only hold the overlay pixels.

`layers` names the texture of each part. `order` is the draw order, bottom first, with "vanilla" for the vanilla
sprite. `flavors` says which custom_model_data string each flavour layer follows; the second layer falls back to the
main flavour when a dish has only one. `raw` marks dishes made without cooking, which also get the raw_ palettes of
their meat, fish and potato. `defaults` are the flavours shown on a stack that was never cooked, such as one taken
from the creative menu.
"""

DISHES = {}

# Bowl dishes sit in the vanilla bowl: rim on row 5, the inside on rows 6-8 (x5-10, x3-11, x5-10).

DISHES["stew"] = dict(
	vanilla="bowl",
	layers={"a": "broth", "b": "chunks"},
	order=["vanilla", "a", "b"],
	defaults=["beef", "carrot"],
	refs=["rabbit_stew", "mushroom_stew", "bowl"],
	grid="""
................
................
................
................
................
......bc12......
.....01cd12.....
...0112ab223....
.....2bc334.....
................
................
................
................
................
................
................
""")

DISHES["soup"] = dict(
	vanilla="bowl",
	layers={"a": "broth", "b": "garnish"},
	order=["vanilla", "a", "b"],
	defaults=["pumpkin", "carrot"],
	refs=["beetroot_soup", "mushroom_stew", "bowl"],
	grid="""
................
................
................
................
................
................
.....011222.....
...0112b2233....
.....22c334.....
................
................
................
................
................
................
................
""")

DISHES["salad"] = dict(
	raw=True,
	vanilla="bowl",
	layers={"a": "pieces", "b": "top"},
	order=["vanilla", "a", "b"],
	defaults=["apple", "sweet_berry"],
	refs=["bowl", "rabbit_stew", "sweet_berries"],
	grid="""
................
................
................
.......556......
.....5ef0126....
....5bcf1236....
.....ab2bc3.....
...12cd23ab3....
.....3d34cd.....
................
................
................
................
................
................
................
""")

# The liquid fills the inside of the vanilla glass bottle, below its highlights.
DISHES["juice"] = dict(
	raw=True,
	vanilla="glass_bottle",
	layers={"a": "liquid"},
	order=["vanilla", "a"],
	defaults=["melon"],
	refs=["honey_bottle", "potion", "melon_slice"],
	grid="""
................
................
................
................
................
................
................
................
................
.....1.01222....
.....1.12223....
.....12223.3....
.....22334.4....
......334.4.....
................
................
""")

# Recolours the chips of the vanilla cookie, so cocoa cookies look like the vanilla one.
DISHES["cookies"] = dict(
	vanilla="cookie",
	layers={"a": "chips"},
	order=["vanilla", "a"],
	defaults=["chocolate"],
	refs=["cookie", "cocoa_beans", "sweet_berries"],
	grid="""
................
................
................
......4.........
................
....3..24.......
..3....34.3.....
.....2..........
.....4..........
.......24..3....
....3...........
.........4......
................
................
................
................
""")

# Recolours the filling of the vanilla pumpkin pie: top surface and the cut face.
DISHES["pie"] = dict(
	vanilla="pumpkin_pie",
	layers={"a": "filling"},
	order=["vanilla", "a"],
	defaults=["pumpkin"],
	refs=["pumpkin_pie", "apple", "sweet_berries"],
	grid="""
................
................
................
................
................
................
.....122221.....
...1221111221...
...2101341122...
..11333411221...
..3333402221....
..333..1........
................
................
................
................
""")

# Recolours the fruit on top of the vanilla cake.
DISHES["cake"] = dict(
	vanilla="cake",
	layers={"a": "fruit"},
	order=["vanilla", "a"],
	defaults=["sweet_berry"],
	refs=["cake", "sweet_berries", "glow_berries"],
	grid="""
................
................
................
.....3.22.......
...3..2123.3....
.......22....2..
....2...........
..........2.....
................
................
................
................
................
................
................
................
""")

# Three chunks centred on a stick that runs corner to corner, in the vanilla stick colours.
STICK = {"T": "#896727", "U": "#684E1E", "V": "#493615", "W": "#281E0B"}

DISHES["skewer"] = dict(
	raw=True,
	layers={"base": "stick", "a": "chunks", "b": "middle"},
	order=["base", "a", "b"],
	defaults=["beef", "carrot"],
	refs=["stick", "sweet_berries", "cooked_beef"],
	pal=STICK,
	grid="""
..............VW
...........556TW
..........50126.
..........51236.
..........52346.
.......ffgT666..
......fabcg.....
......fbcdg.....
......fcdeg.....
...556Tggg......
..50126.........
..51236.........
..52346.........
.VT666..........
VUW.............
WW..............
""")

# Two slices of bread, the top one showing its crumb, with the filling between them.
BREAD = {
	"O": "#3F2E0E", "P": "#654B17", "K": "#8C661E", "J": "#A27924", "D": "#BC8927",
	"W": "#ECD29A", "V": "#DDBB7A", "U": "#C59E5A",
}

DISHES["sandwich"] = dict(
	raw=True,
	layers={"base": "bread", "a": "filling", "b": "bits"},
	order=["base", "a", "b"],
	defaults=["porkchop"],
	refs=["bread", "cooked_porkchop", "cake"],
	pal=BREAD,
	grid="""
................
................
................
...PPPPPPPPPP...
..PJWWWWVVVVKO..
.PJWWVWVVVVVUKO.
.PJVVVVVVVVUUKO.
.PDJJJJJJJJJKKO.
.50112b1222c2346
.5c2233322b33346
.PDJJ3JJJ4JJKKO.
.PKKKKKKKKKKKKO.
..OOOOOOOOOOOO..
................
................
................
""")

KELP = {
	"H": "#6E6A5A", "K": "#57503F", "L": "#3C3324", "M": "#2E2820", "N": "#473F31",
	"X": "#26231E", "Y": "#0F0E0C",
}

DISHES["kelp_roll"] = dict(
	raw=True,
	layers={"base": "wrap", "a": "filling"},
	order=["base", "a"],
	defaults=["salmon"],
	refs=["dried_kelp", "cooked_salmon", "cooked_cod"],
	pal=KELP,
	grid="""
................
..........XXX...
.........XNNNY..
........XN012NY.
.......XXN123NY.
......XHXN233NY.
.....XHKKYNNNY..
....XHKKLLYYY...
...XHKKLLMMY....
..XHKKLLMMY.....
.XHKKLLMMY......
..YKLLMMY.......
...YLMMY........
....YMY.........
.....Y..........
................
""")

EGG = {
	"H": "#FFF0A0", "K": "#F6D85A", "L": "#E8BE3A", "M": "#C89A22", "S": "#DDB040",
	"N": "#A07818", "O": "#6E5010",
}

DISHES["omelette"] = dict(
	layers={"base": "egg", "a": "filling"},
	order=["base", "a"],
	defaults=["mushroom"],
	refs=["egg", "baked_potato", "cooked_chicken"],
	pal=EGG,
	grid="""
................
................
................
................
....556..5566...
..N501266501236.
.NHHKKKKKKKKLLO.
.NHKKKSKKKKLLMO.
.NKKKKKKKSKLLMO.
..NKKSKKKKLLMO..
...NLLLLLLLMO...
.....OOOOOOO....
................
................
................
................
""")

DISHES["roast"] = dict(
	layers={"a": "main", "b": "side"},
	order=["a", "b"],
	defaults=["beef", "potato"],
	refs=["cooked_porkchop", "cooked_mutton", "baked_potato"],
	grid="""
................
................
................
...555566.......
..50111226......
.5011122336.....
.5113122336ffg..
.512223234fabcg.
.513223334fbcdg.
..52333446fcdeg.
...6666ffg.ggg..
......fabcg.....
......fbcdg.....
......fcdeg.....
.......ggg......
................
""")

MUSH = {
	"A": "#8A7E6A", "B": "#74684F", "C": "#5E5440", "D": "#4A4232", "E": "#383226",
	"F": "#50473A", "G": "#221E16", "H": "#A89A80",
}

DISHES["dubious_mush"] = dict(
	layers={"base": "lump"},
	order=["base"],
	refs=["rotten_flesh", "brown_mushroom", "poisonous_potato"],
	pal=MUSH,
	grid="""
................
................
................
................
.....FFG........
...FFABBGFFG....
..FABBCBBAABG...
.FABCCBHCBBCCG..
.FBCCDCCCCDCDG..
FBCDCCDCHCDDDEG.
FCCDDCDDDDDEEG..
.GDDEDDEEEEEGG..
..GGGGGGGGGG....
................
................
................
""")
